version: "3"

tasks:
  lint:
    desc: Run "golangci-lint" in all packages
    cmds:
      - cmd: dagger call lint --root=.

  local-lint:
    desc: Run "golangci-lint" in all packages with the go.work
    cmds:
      - |
        for i in $(find . -name 'go.mod'); do
          if [[ "$i" == "./.github/go.mod" ]]; then
            continue
          fi
          pushd ${i:0:-6} 1>/dev/null
          echo $i
          golangci-lint run || true
          popd 1>/dev/null
        done

  local-test:
    desc: Run "go test ./..." in all packages with the go.work
    cmds:
      - |
        for i in $(find . -name 'go.mod'); do
          if [[ "$i" == "./.github/go.mod" ]]; then
            continue
          fi
          pushd ${i:0:-6} 1>/dev/null
          echo $i
          OUT=$(go test ./... -v -race -cover 2>&1)
          if [[ $? -ne 0 ]]; then
            echo $OUT
            exit 1
          fi
          popd 1>/dev/null
        done

  mod-tidy:
    desc: Run "go mod tidy" in all packages
    cmds:
      - cmd: dagger call tidy --root=. source export --path=.

  mod-update:
    desc: Run "go get -u -t ./..." in all packages
    cmds:
      - cmd: dagger call update --root=. source export --path=.

  test:
    desc: Run "go test ./..." in all packages
    cmds:
      - cmd: dagger call test --root=.

  deps:
    desc: Update dependencies on all changed packages to the latest git commit
    cmds:
      - cmd: GOSUMDB=off GOPROXY="direct" ./scripts/deps.sh main all
