// Code generated by protoc-gen-go-orb-http. DO NOT EDIT.
//
// version:
// - protoc-gen-go-orb-http  v1.0.0
// - protoc                 v4.25.1
//
// Proto source: echo.proto

package proto

import (
	"context"

	"google.golang.org/grpc"

	"github.com/go-orb/go-orb/server"

	mhttp "github.com/go-orb/plugins/server/http"
)

type OrbStreamsHandler interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
	mustEmbedUnimplementedStreamsServer()
}

type UnsafeOrbStreamsServer struct{}

func (s *UnsafeOrbStreamsServer) mustEmbedUnimplementedStreamsServer() {}

// RegisterStreamsHTTPHandler registers the service to an HTTP server.
func RegisterStreamsHTTPHandler(srv *mhttp.ServerHTTP, handler OrbStreamsHandler) {
	r := srv.Router()
	r.Post("/echo.Streams/Call", mhttp.NewGRPCHandler(srv, handler.Call))
}

// RegisterStreamsHandler will return a registration function that can be
// provided to entrypoints as a handler registration.
func RegisterStreamsHandler(handler any) server.RegistrationFunc {
	return server.RegistrationFunc(func(s any) {
		switch srv := any(s).(type) {
		case *mhttp.ServerHTTP:
			RegisterStreamsHTTPHandler(srv, handler.(OrbStreamsHandler))
		case grpc.ServiceRegistrar:
			RegisterStreamsServer(srv, handler.(StreamsServer))
		default:
			// Maybe we should log here with slog global logger
		}
	})
}
