// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.33
// source: echo.proto

package proto

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_echo_proto struct{}

func (drpcEncoding_File_echo_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_echo_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_echo_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_echo_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_echo_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCStreamsClient interface {
	DRPCConn() drpc.Conn

	Call(ctx context.Context, in *CallRequest) (*CallResponse, error)
}

type drpcStreamsClient struct {
	cc drpc.Conn
}

func NewDRPCStreamsClient(cc drpc.Conn) DRPCStreamsClient {
	return &drpcStreamsClient{cc}
}

func (c *drpcStreamsClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcStreamsClient) Call(ctx context.Context, in *CallRequest) (*CallResponse, error) {
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, "/echo.Streams/Call", drpcEncoding_File_echo_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCStreamsServer interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
}

type DRPCStreamsUnimplementedServer struct{}

func (s *DRPCStreamsUnimplementedServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCStreamsDescription struct{}

func (DRPCStreamsDescription) NumMethods() int { return 1 }

func (DRPCStreamsDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/echo.Streams/Call", drpcEncoding_File_echo_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCStreamsServer).
					Call(
						ctx,
						in1.(*CallRequest),
					)
			}, DRPCStreamsServer.Call, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterStreams(mux drpc.Mux, impl DRPCStreamsServer) error {
	return mux.Register(impl, DRPCStreamsDescription{})
}

type DRPCStreams_CallStream interface {
	drpc.Stream
	SendAndClose(*CallResponse) error
}

type drpcStreams_CallStream struct {
	drpc.Stream
}

func (x *drpcStreams_CallStream) SendAndClose(m *CallResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_echo_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
