// Code generated by protoc-gen-go-orb. DO NOT EDIT.
//
// version:
// - protoc-gen-go-orb        v0.0.1
// - protoc                   v5.27.3
//
// source: echo.proto

package proto

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_echo_proto struct{}

func (drpcEncoding_File_echo_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_echo_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_echo_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_echo_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_echo_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCStreamsServer interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
	AuthorizedCall(context.Context, *CallRequest) (*CallResponse, error)
}

type DRPCStreamsUnimplementedServer struct{}

func (s *DRPCStreamsUnimplementedServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCStreamsUnimplementedServer) AuthorizedCall(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCStreamsDescription struct{}

func (DRPCStreamsDescription) NumMethods() int { return 2 }

func (DRPCStreamsDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/echo.Streams/Call", drpcEncoding_File_echo_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCStreamsServer).
					Call(
						ctx,
						in1.(*CallRequest),
					)
			}, DRPCStreamsServer.Call, true
	case 1:
		return "/echo.Streams/AuthorizedCall", drpcEncoding_File_echo_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCStreamsServer).
					AuthorizedCall(
						ctx,
						in1.(*CallRequest),
					)
			}, DRPCStreamsServer.AuthorizedCall, true
	default:
		return "", nil, nil, nil, false
	}
}

type DRPCStreams_CallStream interface {
	drpc.Stream
	SendAndClose(*CallResponse) error
}

type drpcStreams_CallStream struct {
	drpc.Stream
}

func (x *drpcStreams_CallStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcStreams_CallStream) SendAndClose(m *CallResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_echo_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCStreams_AuthorizedCallStream interface {
	drpc.Stream
	SendAndClose(*CallResponse) error
}

type drpcStreams_AuthorizedCallStream struct {
	drpc.Stream
}

func (x *drpcStreams_AuthorizedCallStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcStreams_AuthorizedCallStream) SendAndClose(m *CallResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_echo_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
