// Code generated by protoc-gen-go-micro-http. DO NOT EDIT.
//
// version:
// - protoc-gen-go-micro-http v1.0.0
// - protoc                   v3.21.7
//
// Proto source: echo.proto

package proto

import (
	"google.golang.org/grpc"

	"go-micro.dev/v5/server"

	mhttp "github.com/go-micro/plugins/server/http"
)

func RegisterStreamsHTTPHandler(srv *mhttp.ServerHTTP, handler StreamsServer) {
	r := srv.Router()
	r.Get("/echo", mhttp.NewGRPCHandler(srv, handler.Call))
	r.Post("/echo", mhttp.NewGRPCHandler(srv, handler.Call))
}

func RegisterFuncStreams(handler StreamsServer) server.RegistrationFunc {
	return server.RegistrationFunc(func(s any) {
		switch srv := any(s).(type) {
		case *mhttp.ServerHTTP:
			RegisterStreamsHTTPHandler(srv, handler)
		case grpc.ServiceRegistrar:
			// RegisterStreamsgRPCHandler(srv, handler)
		default:
			// Maybe we should log here with slog global logger
		}
	})
}
